
eureka:
  instance:
    prefer-ip-address: true  # Ensures that Eureka uses the IP address for this instance
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9095/eureka}  # Eureka server URL
    register-with-eureka: true  # Registers the service with Eureka
    fetch-registry: true  # Fetches the registry of services from Eureka
